# Site settings
title:  大少博客
SEOTitle: 雷大少 | leidashao.githob.io
header-img: img/home-bg.jpg
email: 1790727569@qq.com
description: "这是雷大少的博客"
keyword: ""
#url: "https://1leidashao.github"              # your host, for absolute URL
baseurl: ""                             # for example, '/blog' if your blog hosted on 'host/blog'

repository: leidashao.github.io

# SNS settings
RSS: false
weibo_username:     http://weibo.com/u/6358267615
zhihu_username:     leidashao.io
github_username:    leidashao
twitter_username:   leidashao

# linkedin_username:  firstname-lastname-idxxxx



# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
highlighter: rouge
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md","README.zh.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`



# Gems
# from PR#40, to support local preview for Jekyll 3.0
gems: [jekyll-paginate]




# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
kramdown:
input: GFM                            # use Github Flavored Markdown !important



# Disqus settings
# disqus_username: leidashao.github.io





# Analytics settings
# Baidu Analytics
# ba_track_id: [your track id]

# Google Analytics
ga_track_id: 'UA-49627206-1'            # Format: UA-xxxxxx-xx
ga_domain:



# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "May I bear the world and do not want the world to bear me"
sidebar-avatar: /img/dashao.jpg      # use absolute URL, seeing it's used in both `/` and `/about/`



# Featured Tags
featured-tags: true                     # whether or not using Feature-Tags
featured-condition-size: 1              # A tag will be featured if the size of it is more than this condition value



# Friends
friends:
  [
  {
        title: "leidashao",
        href: "https://user.qzone.qq.com/1790727569?ADUIN=2496102279&ADSESSION=1516978241&ADTAG=CLIENT.QQ.5551_FriendTip.0&ADPUBNO=26765&source=namecardhoverstar"
    },
  {
        title: "大少推荐",
        href: "https://www.ruiwen.com/zhaichao/1061291.html"
    }
]
